name = "nordic-cheats-docs"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[kv_namespaces]]
binding = "DOC_OVERRIDES"
id = "693e7fbafad24bd0aa22c9a6b478d59c"
