name = "nordic-cheats-docs"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[kv_namespaces]]
binding = "DOC_OVERRIDES"
id = "e230c672ce9c4c4e88d2f62def8054b0"
